-- Nora website assistant storage.
-- Browser clients never query these tables directly; the public Edge Function uses service_role.

create table if not exists public.nora_web_sessions (
  id uuid primary key default gen_random_uuid(),
  visitor_id text not null,
  status text not null default 'active' check (status in ('active','qualified','lead_created','closed')),
  stage text not null default 'welcome',
  product_interest text check (product_interest in ('assistants','marketing','solutions','exploring')),
  goal text,
  full_name text,
  business_name text,
  email text,
  phone text,
  industry text,
  privacy_consent boolean not null default false,
  source_path text,
  landing_path text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  lead_id uuid references public.demo_requests(id) on delete set null,
  message_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_message_at timestamptz not null default now()
);

create index if not exists nora_web_sessions_visitor_idx on public.nora_web_sessions(visitor_id, created_at desc);
create index if not exists nora_web_sessions_status_idx on public.nora_web_sessions(status, last_message_at desc);
create index if not exists nora_web_sessions_product_idx on public.nora_web_sessions(product_interest, created_at desc);

create table if not exists public.nora_web_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.nora_web_sessions(id) on delete cascade,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists nora_web_messages_session_idx on public.nora_web_messages(session_id, created_at);

create table if not exists public.nora_web_rate_limits (
  rate_key text primary key,
  window_start timestamptz not null,
  request_count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.nora_web_sessions enable row level security;
alter table public.nora_web_messages enable row level security;
alter table public.nora_web_rate_limits enable row level security;

revoke all on table public.nora_web_sessions from anon, authenticated;
revoke all on table public.nora_web_messages from anon, authenticated;
revoke all on table public.nora_web_rate_limits from anon, authenticated;

grant all on table public.nora_web_sessions to service_role;
grant all on table public.nora_web_messages to service_role;
grant all on table public.nora_web_rate_limits to service_role;
grant usage, select on sequence public.nora_web_messages_id_seq to service_role;

drop trigger if exists touch_nora_web_sessions_updated_at on public.nora_web_sessions;
create trigger touch_nora_web_sessions_updated_at
before update on public.nora_web_sessions
for each row execute function private.set_updated_at();


-- Explicit browser denial policies. Edge Functions use service_role and bypass these.
drop policy if exists "deny browser access nora sessions" on public.nora_web_sessions;
create policy "deny browser access nora sessions"
on public.nora_web_sessions as restrictive for all
to anon, authenticated
using (false)
with check (false);

drop policy if exists "deny browser access nora messages" on public.nora_web_messages;
create policy "deny browser access nora messages"
on public.nora_web_messages as restrictive for all
to anon, authenticated
using (false)
with check (false);

drop policy if exists "deny browser access nora rate limits" on public.nora_web_rate_limits;
create policy "deny browser access nora rate limits"
on public.nora_web_rate_limits as restrictive for all
to anon, authenticated
using (false)
with check (false);
